Feature/theme emotion
pickly-team/pickly-frontend pull request #12
Opened 2023-02-15 13:21 UTC by aeong98

## 📌 개요 (필수)

- resolve #12
- 이모션 컬러팔레트 색상 설정, 테스트용 Checkbox 컴포넌트 생성

<br>

## 🔨 작업 사항 (필수)
<img width="207" alt="image" src="https://user-images.githubusercontent.com/51521314/219038333-66334e0e-5fed-4ceb-9fc7-227c6d017f27.png">
- 이모션 컬러팔레트 색상 추가
- CheckBox 컴포넌트 생성
- CheckBox에 필요한 아이콘 컴포넌트 추가 

<br>

## ⚡️ 관심 리뷰 (선택)
- 원래 SVG아이콘 컴포넌트 만들때 어떻게하시나용?
- CheckBox 컴포넌트 인터페이스 알맞게 지어졌는지 리뷰 부탁드립니당

<br>

## 🌱 연관 내용 (선택)
- [피그마](https://www.figma.com/file/QzYU4yAZa0RC56Y8DxzPol/Pickly-team-library?node-id=581%3A11680&t=F07Nu9CiDKOV3bYj-1)

**+) 예제 코드는 Approve 이후 삭제할 예정입니다. (Test.tsx)**

2023-02-15 13:22 UTC, aeong98 commented on src/components/Test.tsx
>  const Test = () => {
어프루브 이후 삭제될 코드입니당

2023-02-15 13:22 UTC, aeong98 commented on src/styles/theme.ts
> +export const theme = {
theme 컬러 색상 제대로 들어갔는지 확인한번만 부탁드려용

2023-02-16 12:18 UTC, ww8007 requested changes
grey 색상 컬러만 변경되면 될 것 같아요! 고생하셨습니다. 😃

2023-02-16 12:18 UTC, ww8007 commented on src/styles/theme.ts
> +    mediumGrey: '#BDBDBD',
grey 경우 material palette를 따라가서 grey 색상 쪽만 변경하면 될 것 같아요!
```ts
    primary: '#76B100',
    lightPrimary: '#A7E100',
    darkPrimary: '#8EC520',
    white: '#ffffff',
    grey200: '#EEEEEE',
    grey400: '#BDBDBD',
    grey600: '#757575',
    grey800: '#424242',
    grey900: '#212121',
```

2023-02-16 12:18 UTC, ww8007 commented on src/common-ui/CheckBox.tsx
> +) => {
JsDoc example를 주석으로 두는거 어떻게 생각하세요?
관리가 제대로 되어야만 의미가 있긴 할테지만 처음 하시는 분들도 계시고 제공을 하면 좀 더 
컴포넌트 사용처에서 이해가 좋지 않을까 해서 제안 드려 봅니다!

2023-02-16 12:18 UTC, ww8007 commented on src/common-ui/CheckBox.tsx
> +) => {
근데 또 생각해보니 테스트 코드가 그 역할을 하는 것 같기도 하고 🧐

2023-02-16 12:18 UTC, ww8007 commented on src/common-ui/CheckBox.test.tsx
> +  describe('개발자 관점 테스트', () => {
ref에 대한 테스트도 추후에 추가되면 좋을 것 같아요

2023-02-16 12:18 UTC, ww8007 commented on src/common-ui/CheckBox.tsx
> +  };
오 ts 책에 나온 좋은 예시네요

2023-02-16 12:18 UTC, ww8007 commented on src/common-ui/icons/CheckCircleIcon.tsx
> +};
아이콘 관련해서는 아이콘 loader를 만들어서 하나로 관리해도 좋을 것 같아요 
관련 코드는 추후 작성해 보겠습니다

2023-02-16 12:36 UTC, aeong98 commented on src/common-ui/icons/CheckCircleIcon.tsx
> +};
좋습니당!!!

2023-02-16 12:36 UTC, aeong98 commented on src/common-ui/CheckBox.test.tsx
> +  describe('개발자 관점 테스트', () => {
엇 넵 담에 enhance로 추가해볼게요 ㅎㅎ

2023-02-16 12:38 UTC, aeong98 commented on src/styles/theme.ts
> +    mediumGrey: '#BDBDBD',
동현님께서 이어서 작업해주시기로 하셧습니당

2023-02-16 12:38 UTC, ww8007 approved these changes
LGTM!

2023-02-16 12:38 UTC, merged