프로필 페이지를 추가합니다.
pickly-team/pickly-frontend pull request #47
Opened 2023-03-13 12:21 UTC by litsynp

## 📌 개요 (필수)

프로필 페이지를 추가합니다.

- Related: #41

<br>

## 🔨 작업 사항 (필수)

- 프로필 페이지를 추가합니다.

- API 연동은 아직입니다.

<br>

![localhost_3000_profile(iPhone X)](https://user-images.githubusercontent.com/42485462/232235098-6698defb-16e6-4da6-95c2-de196aa5a101.png)

2023-03-14 16:10 UTC, ww8007 approved these changes
첫 프론트엔드 테스크 고생하셨습니다 😃
역시 Ocean

2023-03-14 16:10 UTC, ww8007 commented on src/members/ui/BasicInfoBox.tsx
> +        <Text.Span fontSize={3}>🥱</Text.Span>
[P1]
요 친구도 외부에서 받아올 수 있도록 추가해야 할 것 같네요!
nickname, email 같이 변경되는 사항이라

2023-03-14 16:10 UTC, ww8007 commented on src/members/ui/StatsBox.tsx
> +          </IconLabelContainer>
[P1]
추후에 이 아이템을 누르면 다른 페이지로 이동해야 해서
Link나 NavLink로 래핑을 해두는게 좋아보여요

2023-03-14 16:10 UTC, ww8007 commented on src/members/ui/ModeInfoBox.tsx
> +  const modedTitle = (isHardMode: boolean) => {
[P3]
혹시 moded라고 의도를 하신걸까요?

2023-03-14 16:10 UTC, ww8007 commented on src/members/ui/ModeInfoBox.tsx
> +        </div>
[P2]
div 태그를 이용하는 것 보다 
1. ModeDescriptionContainer에서 Span 사이 marginTop
2. 스타일 컴포넌트로 생성하여 래핑
방식이 더 좋아보일 것 같아요

이것도 나중에 스타일링 잡을 때 잡아도 될 듯 합니다

2023-03-14 16:10 UTC, ww8007 commented on src/members/ui/ModeInfoBox.tsx
> +        </Text.Div>
[P2]
혹시 아래와 다르게 이 친구만 Div로 설정하신 이유가 있을까요?

2023-03-14 16:10 UTC, ww8007 commented on src/members/ui/ModeInfoBox.tsx
> +        </Text.Div>
그리고 이 친구들 최종 디자인 사항에 bold가 아니라 빼주시면 감사하겠습니다 👍

2023-03-14 16:10 UTC, ww8007 commented on src/members/ui/NotificationSettingBox.tsx
> +    <Button width={40} disabled style={{ fontWeight: 'bold' }}>
[P3]
이 친구도 bold가 아닌 것 같아요 
추후 스타일 잡을 때 잡아도 될듯 합니다 👍

2023-03-14 16:10 UTC, ww8007 commented on src/utils/numberWithCommas.ts
[P2]
추후 테스트 코드 추가하면 좋겠네요 
저도 아직 안해서 ㅋㅋㅋ...

2023-03-14 16:10 UTC, ww8007 commented on src/members/ui/ModeInfoBox.tsx
> +        </ButtonContainer>
[P3]
개인적인 의견으로 각각의 아이템이 어떤 것을 의미하는지 주석으로 위에 달아둬도 
괜찮을 것 같네요 
이 아이템이 어떤 것을 보여주는지 담는 부분까지 가는게 생각보다 depth가 있어서

2023-03-24 11:18 UTC, litsynp commented on src/members/ui/ModeInfoBox.tsx
> +  const modedTitle = (isHardMode: boolean) => {
넵ㅋㅋ mode가 적용된 -> moded... @ww8007

2023-03-24 14:44 UTC, litsynp commented on src/members/ui/ModeInfoBox.tsx
> +        </div>
이건 이름 짓기 너무 애매하긴 한데... (2번째 줄인 것 말곤 특징이 없어서?) 일단 2번으로 가져가볼게요.

2023-03-24 14:44 UTC, litsynp commented on src/members/ui/ModeInfoBox.tsx
> +        </Text.Div>
줄바꾸는 부분은 div로 두긴 했습니다! Span으로 바꿔둘게요

2023-03-24 14:52 UTC, litsynp commented on src/members/ui/ModeInfoBox.tsx
> +        </ButtonContainer>
디자인이 조금씩 바뀌고 있는 것 같아서 주석 관리가 어려울 것 같긴 합니다 (작성하는 순간 deprecation 시작이라...)
코드 읽으면서 무리가 없다면 제외해도 괜찮지 않을까요?

2023-03-25 19:02 UTC, ww8007 commented on src/common-ui/RoundToggle.tsx
> +};
쓰읍 열심히 만드셨는데 UI에서 사라져 버려서 슬프네요 ㅠㅠ
추후 MVP 이후에 다시 사용될 것 같긴 한데 그래도 예쁘게 잘 나온 것 같습니다 🫠

2023-03-25 19:04 UTC, ww8007 commented on src/common-ui/RoundToggle.tsx
> +  setOff: () => void;
[P2] 
interface를 사용해서 다음과 같이 적어도 괜찮을 것 같아요
```tsx
interface RoundToggleProps {
    transitionMs?: number;
    isOn?: boolean;
    setOn: () => void;
    setOff: () => void;
} & HTMLAttributes<HTMLDivElement>;

2023-03-25 19:22 UTC, ww8007 requested changes
LGTM! 고생하셨습니다!!
의견 남겨두었는데 UI가 또 바뀌어서... 죄송합니다 엉엉😂

2023-03-25 19:22 UTC, ww8007 commented on src/members/ui/BasicInfoBox.tsx
> +  const numberFormatter = new Intl.NumberFormat('en', { notation: 'compact' });
[P3]
오 요런것도 있군요 👍

2023-03-25 19:22 UTC, ww8007 commented on src/members/ui/CustomerFeedbackBox.tsx
> +      >
[P2]
이 친구도 아래와 같이 사용해서 재사용 하여도 좋을 것 같네요 
```tsx
const StyledLink = styled(Link)`
   width: 100%;
`
```

2023-03-25 19:22 UTC, ww8007 commented on src/members/ui/ModeInfoBox.tsx
> +      }}
[P2]
이 친구들 아래 Styled로 내려도 될 것 같긴 하네요

2023-03-25 19:22 UTC, ww8007 commented on src/members/ui/NotificationSettingBox.tsx
> +}) => {
[P1]
저희  컨벤션을 정확히 않았긴 했는데 interface를 사용해서 Props로 선언하는걸 통일 시켜도 좋을 것 같아요!

2023-03-25 19:22 UTC, ww8007 commented on src/notification/api/notification.ts
> +};
[P3] 
깔끔하고 좋네요 👍

2023-03-25 19:22 UTC, ww8007 commented on src/members/ui/RoundedBox.tsx
> +  border?: { borderColor: ColorType };
[P2]
이 경우 굳이 객체로 받지 않아도 될 것 같아요
border에 대해서 확장성이 열린게 컬러 뿐이니 borderColor로 받아도 괜찮을 듯 합니다 😃

2023-03-25 19:22 UTC, ww8007 commented on src/members/ui/BasicInfoBox.tsx
> +  height: 5.5rem;
[P1]
반응형을 고려하면 이런 친구들도 `getRem`으로 감싸야 할 것 같아요

2023-03-25 19:24 UTC, ww8007 commented on src/members/ui/ModeInfoBox.tsx
> +        </ButtonContainer>
흠 그것도 맞는거 같네요 UI 아마 오늘로써 거의 확정이니 단위단위 구분만 잘 된다면 문제 없을듯 합니다 😃

2023-03-25 19:26 UTC, ww8007 reviewed
LGTM! 고생하셨습니다!!
의견 남겨두었는데 UI가 또 바뀌어서... 죄송합니다 엉엉😂

2023-03-26 07:19 UTC, aeong98 reviewed
와우 고생하셧습니당 👍 ㅎㅎ

2023-03-26 07:19 UTC, aeong98 commented on src/members/ui/BasicInfoBox.tsx
> +  const numberFormatter = new Intl.NumberFormat('en', { notation: 'compact' });
[p3] 요 포맷팅함수 service쪽으로 빼고 테스트코드 작성해줘도 될것같습니답.

2023-03-26 07:19 UTC, aeong98 commented on src/members/ui/ModeInfoBox.tsx
> +  daysPassedSinceCurrentMode: number;
요건 사용하지 않는데 왜 props로 선언해주신거에용??

2023-03-26 07:19 UTC, aeong98 commented on src/members/ui/ModeInfoBox.tsx
> +      }
요거 그냥 인라인 해줘도 될것같습니당?

```suggestion
      onClick={onClick}
```

2023-03-26 07:19 UTC, aeong98 commented on src/members/ui/ModeInfoBox.tsx
> +        cursor: onClick ? 'pointer' : 'default',
요거 스타일링을 onClick일 때만 pointer로 해주신 이유가 궁금해용! 컴포넌트 네이밍이 button이고 클릭 이벤트를 전달하는 역할의 컴포넌트면 아래 코멘트처럼 button으로 만들고 cursor 스타일링을 주지 않는것도 방법일 것 같습니답!!

2023-03-26 07:19 UTC, aeong98 commented on src/members/ui/ModeInfoBox.tsx
> +const StyledCircleButton = styled.div`
요거 네이밍에 맞춰서 div 대신 button tag을 사용해줘도 좋을것같습니다!

2023-03-26 07:19 UTC, aeong98 commented on src/members/ui/NotificationSettingBox.tsx
> +  const getDayOfWeekColor = (dayOfWeek: string) => {
[p2] 
해당 함수를 daily를 포함하는지를 판단하는 함수와, weekly인지를 포함하는 함수로 분리해서 각 로직별로 관심사를 분리해도 좋을것같습니당! 

+) service로 빼서 테스트코드 작성해놔도 좋을것같아용

2023-03-26 07:19 UTC, aeong98 commented on src/members/ui/StatsBox.tsx
> +              <Text.Span style={{ marginLeft: '0.8rem' }}>좋아요</Text.Span>
```suggestion
const IconText = styled(Text.Span)`
  margin-left: 0.8rem;
`

<IconText>좋아요</IconText>
```
[p2] 위와 같이 styled component로 선언해서 스타일링해줘도 좋을것같습니당

2023-03-26 07:19 UTC, aeong98 commented on src/notification/api/notification.ts
> +};
굳굳~~~

2023-03-26 07:19 UTC, aeong98 commented on src/notification/api/notification.ts
> +  type: 'weekly';
이것은 태깅..?

2023-03-26 07:19 UTC, aeong98 commented on src/utils/numberWithCommas.ts
> +export function numberWithCommas(x: number): string {
[p3] 만약에 가능하시면 util 테스트 코드 작성해주면 좋을것같습니당 ㅎㅎ

2023-03-27 10:56 UTC, litsynp commented on src/notification/api/notification.ts
> +  type: 'weekly';
예스! 🫡 @aeong98

2023-04-07 13:20 UTC, litsynp commented on src/members/ui/NotificationSettingBox.tsx
> +}) => {
저는 사용처랑 가까운게 읽기 편한 것 같긴 한데 통일하면 좋은 점이 있나요? @ww8007

2023-04-07 13:26 UTC, litsynp commented on src/members/ui/ModeInfoBox.tsx
> +  daysPassedSinceCurrentMode: number;
아 이건 이전 디자인의 잔여물인데... ESLint에서 unused variable을 안잡아주네요; 일단 삭제하겠습니당

2023-04-07 13:31 UTC, litsynp commented on src/members/ui/ModeInfoBox.tsx
> +        cursor: onClick ? 'pointer' : 'default',
요건 다른 유즈케이스가 없으니 onClick 강제할게요!

2023-04-07 13:40 UTC, ww8007 commented on src/members/ui/NotificationSettingBox.tsx
> +}) => {
추후 유지보수를 진행할 때 같은 이해관계를 가지고 컴포넌트를 바라보았으면 했는데 이 정도는 각자의 자율성에 맞추어도 문제가 없을듯 하네요 👍

2023-04-07 15:21 UTC, litsynp commented on src/members/ui/NotificationSettingBox.tsx
> +  const getDayOfWeekColor = (dayOfWeek: string) => {
디자인 변경으로 삭제합니당

2023-04-07 15:21 UTC, litsynp commented on src/members/ui/BasicInfoBox.tsx
> +  height: 5.5rem;
getRem === rem 같은거 아닌가용?

2023-04-07 16:40 UTC, ww8007 commented on src/members/ui/BasicInfoBox.tsx
> +  height: 5.5rem;
서연님이 작성해주신 getRem 함수가 `fontSize : 62.5%` 기준 -> `10px === 1rem` 이라서
만약 55px이 맞다면 그대로 작성하여도 문제가 없을듯 하네요

2023-04-07 17:17 UTC, ww8007 reviewed
고생하셨습니다! 
현재  PC에서 시간 input에 대해서 문제가 있는거 같아서 의견 남겨두었습니다!
혹시 최상단 more 버튼에 대해서는 아직 처리가 안된게 맞는거죠?

2023-04-07 17:17 UTC, ww8007 commented on src/utils/numberWithCommas.test.ts
> +    expect(numberWithCommas(-2000.001)).toStrictEqual('-2,000.001');
[P3]
👍

2023-04-07 17:17 UTC, ww8007 commented on src/pages/ProfilePage.tsx
> +  padding: 0 20px;
[P1]
getRem으로 바꿔야 할 것 같아요

2023-04-07 17:17 UTC, ww8007 commented on src/members/ui/CustomerFeedbackBox.tsx
> +        </RoundedBox>
[P1]
오른쪽 화살표 아이콘이 빠진거 같아요!
확인 부탁드리겠습니다

2023-04-07 17:17 UTC, ww8007 commented on src/members/ui/NotificationSettingsBottomSheet.tsx
> +            }}
[P3]
기본 Button에 이 처리가 안되어 있었군요...
처리 감사 드립니다 추후에 공통 UI 버튼에 추가해둘게요 😂

2023-04-07 17:17 UTC, ww8007 commented on src/members/ui/NotificationSettingsBottomSheet.tsx
> +`;
[P1]
} 닫는게 빠진거 같아요!

2023-04-07 17:17 UTC, ww8007 commented on src/members/ui/NotificationSettingsBottomSheet.tsx
> +      ></StyledNumberInput>
[P2]
Self-Closing으로 처리하여도 될듯 하네요
```tsx
<StyledNumberInput/>
```

2023-04-07 17:17 UTC, ww8007 commented on src/members/ui/NotificationSettingsBottomSheet.tsx
> +      ></StyledNumberInput>
[P1]
현재 로직 상으로 조금 문제가 있는거 같아요!
시간 입력에 대해서 키보드를 통해 입력하게 되면 592 같이 늘어나게 되어 있어서 제대로 입력이 들어가지 않는 것 같아요 ㅠㅠ 
다음과 같은 로직으로 처리할 수 있을 것 같네요
```ts
    if (e.target.value.length > 2) {
      const minuteElement = document.getElementById(
        'minute',
      ) as HTMLInputElement;
      if (minuteElement) {
        minuteElement.value = minuteElement.value.slice(-1);
        setMinute(Number(minuteElement.value));
      }
      return;
    }
```

2023-04-07 17:17 UTC, ww8007 commented on src/members/ui/NotificationSettingsBottomSheet.tsx
> +        <InputContainer>
[P2]
이 친구 뭔가 Bold인거 같은데 확인해 주시면 감사하겠습니다

2023-04-07 17:17 UTC, ww8007 commented on src/members/ui/SettingsBox.tsx
> +      </StyledTitle>
[P2]
이 친구도 Bold인거 같은데 확인 부탁드립니다

2023-04-07 17:17 UTC, ww8007 commented on src/members/ui/BasicInfoBox.tsx
> +          <Icon name={'circle-pencil'} size={'l'} />
[P1]
혹시 이 페이지가 다른 유저의 프로필을 방문했을 때도 재사용될 예정이라면
user 정보가 같을 때만 이 아이콘이 나와야 할 것 같아요!

2023-04-07 17:17 UTC, ww8007 commented on src/common-ui/RoundToggle.tsx
> +  top: calc(50% - 15px);
[P2]
이 친구들도 getRem으로 처리해주시면 감사하겠습니다!

2023-04-15 15:22 UTC, litsynp commented on src/members/ui/BasicInfoBox.tsx
> +          <Icon name={'circle-pencil'} size={'l'} />
페이지가 재사용될것 같진 않지만... 컴포넌트가 재사용될 여지는 있을 것 같긴 합니다.
하지만 아직 API가 연동이 되어있지 않아 추후 리팩토링하면 될 듯 합니다!

2023-04-15 15:26 UTC, litsynp commented on src/members/ui/SettingsBox.tsx
> +      </StyledTitle>
이 친구는 이미 적용이 돼있습니다!

2023-04-15 15:47 UTC, litsynp commented
More 버튼도 완료! @ww8007

2023-04-16 05:19 UTC, ww8007 reviewed
정말 고생 많으셨습니다 😃

근데... 지금 인터렉션이 조금 잘못된거 같아요
현재 설정 버튼을 누르면 나와야 하는 화면은 아래 화면이고
<img width=300 src="https://user-images.githubusercontent.com/54137044/232272508-eef89600-42d5-4e55-812b-1261d18d1f01.png"/>

알림에 대한 토글을 ON 시켰을 때 > 유저가 알림을 선택시
현재 설정 버튼을 눌렀을 때 나오는 BS가 나와야 해서
이것만 수정해 주신다면 정말 감사드리겠습니다 😂
![image](https://user-images.githubusercontent.com/54137044/232272503-c24b8516-c5a3-4053-a454-aac88f7cf8b2.png)

2023-04-16 05:19 UTC, ww8007 commented on src/common-ui/RoundToggle.tsx
> +          transform: translateX(38px);
[P3]
이것도 추후에 반응형으로 잡아도 좋을 것 같네요 👍

2023-04-16 05:19 UTC, ww8007 commented on src/members/ui/BasicInfoBox.tsx
> +            </Link>
[P3]
이 친구 추후에 flex만 적용되어도 좋을 것 같아요 👍

2023-04-16 15:53 UTC, litsynp commented on src/common-ui/RoundToggle.tsx
> +          transform: translateX(38px);
넵 이건 당장은 어려워서... 추후에 반영할게요!

2023-04-22 14:51 UTC, ww8007 approved these changes
정말 고생 많으셨습니다 👍 LGTM

2023-04-22 14:51 UTC, ww8007 commented on src/members/ui/NotificationSettingBox.tsx
> +          }
[P2]
```tsx
onClick={() => isNotificationOn && open()}
```

다음과 같이 사용해도 좋을듯 하네요

2023-04-22 15:37 UTC, merged