feat : 멤버 Comment List 페이지 추가
pickly-team/pickly-frontend pull request #84
Opened 2023-05-21 15:29 UTC by JoeCP17

## 📌 개요 (필수)

- resolve #58 
- PR의 메인 내용

1. 멤버 댓글 조회 리스트 추가 

1. 멤버 코멘트 
<br>

## 🔨 작업 사항 (필수)

- 추가 또는 변경된 내용을 적어주세요.

1. 멤버 코멘트 리스트 페이지 구현을 하였습니다. 
2. 피그마 UI를 기반으로 UI 구성을 진행하였습니다. 

<br>

## ⚡️ 관심 리뷰 (선택)

- 특별히 확인 받고 싶은 내용을 적어주세요. 

<br>

## 🌱 연관 내용 (선택)

- 관련 있는 내용, 또는 앞으로 고려할 내용을 적어주세요.

2023-05-23 01:20 UTC, ww8007 requested changes
LGTM! 첫 프론트 테스크 고생하셨습니다 👍
서버 endpoint 주소만 env로 관리되게 바뀌면 될 것 같네요

2023-05-23 01:20 UTC, ww8007 commented on src/comment/ui/comment-list/CommentItem.tsx
> +const CommentList = ({
[P2]
오잉 컴포넌트 이름이랑 파일 이름이랑 다른거 같아요
`CommentItem`, `CommentList` export default라 상관 없기는 하겠지만 
수정하면 좋을 것 같아요!

2023-05-23 01:20 UTC, ww8007 commented on src/comment/api/Comment.ts
> +const BASE_URL = 'http://52.79.54.119:8080/api';
[P1]
서버 주소의 경우 env로 관리 하기로 해서 제거 해주시면 좋을 것 같아요
밑에 axios를 client로 변경하시면 됩니다!

2023-05-23 01:20 UTC, ww8007 commented on src/comment/api/Comment.ts
> +import axios from 'axios';
[P1]
이와 같이 변경하고 아래 코드 내용도 변경해주시면 좋을 것 같네요 👍
```ts
import client from ‘@/common/service/client’;
```

2023-06-25 13:33 UTC, JoeCP17 commented on src/comment/ui/comment-list/CommentItem.tsx
> +const CommentList = ({
오 .... 이제서야 발견했지만 좋은 지적해주셔서 감사합니당 수정해놓을게요!

2023-06-25 13:34 UTC, JoeCP17 commented on src/comment/api/Comment.ts
> +const BASE_URL = 'http://52.79.54.119:8080/api';
으악.... 이런 기초적인 실수를...!!! 수정해두겠습니다!

2023-06-25 13:34 UTC, JoeCP17 commented on src/comment/api/Comment.ts
> +import axios from 'axios';
수정하겠습니당 감사해용!

2023-06-25 14:11 UTC, ww8007 approved these changes
LGTM! 고생하셨습니다 😃
한 달만의 머지라니 이건 좀 귀하네요 
쉽지 않은 사람 조킴...

2023-06-25 14:11 UTC, ww8007 commented on src/pages/CommentPage.tsx
> +                key={comment.id} // 변경이 되었는지 안되었는지 판단 여부
[p3]
귀엽네요 ㅋㅋ

2023-06-25 14:11 UTC, ww8007 commented on src/comment/api/Comment.ts
> +};
[p3]
GOOD!

2023-06-25 14:16 UTC, merged